# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - rchk
  pull_request:
    branches:
      - rchk

name: rchk

jobs:
  rchk:
    runs-on: ubuntu-latest
    container:
      image: rhub/ubuntu-rchk
      options: --user=root
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/run-rchk@v2
      with:
        setup-only: true
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: rchk-1
    - uses: r-lib/actions/run-rchk@v2
      with:
        run-only: true
        