# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - valgrind
  pull_request:
    branches:
      - valgrind

name: valgrind

jobs:
  valgrind:
    runs-on: ubuntu-latest
    container: wch1/r-debug
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: RDscript {0}

      - name: Install package
        run: RD CMD INSTALL .
        
      - name: Save TMB objects
        run: |
          library(SAMtool)
          OM <- testOM
          OM@CAA_ESS <- c(0.1, 0.1) 
          Hist <- MSEtool::Simulate(OM, silent = TRUE)
          
          assess <- c("DD_TMB", "DD_SS", "SCA", "SCA2", "SCA_Pope", "SCA_RWM", "SP", "SP_SS", "VPA", "RCM_assess")
          assess_sim <- lapply(assess, do.call, args = list(Data = Hist@Data))
          names(assess_sim) <- assess
          saveRDS(assess_sim, file = "assess_sim.rds")
          
          RS <- MSEtool::Red_snapper
          RS@sigmaR <- 0.6
          assess_rs <- lapply(assess[!grepl("VPA", assess)], do.call, args = list(Data = RS))
          names(assess_rs) <- assess[!grepl("VPA", assess)]
          saveRDS(assess_rs, file = "assess_rs.rds")
          
          data(pcod) 
          mat_ogive <- pcod$OM@cpars$Mat_age[1, , 1]
          out <- RCM(OM = SubCpars(pcod$OM, 1:2), data = pcod$data, 
           condition = "catch", mean_fit = TRUE,
           selectivity = "free", s_selectivity = rep("SSB", ncol(pcod$data@Index)),
           vul_par = matrix(mat_ogive, length(mat_ogive), 1),
           map_vul_par = matrix(NA, length(mat_ogive), 1),
           map_log_early_rec_dev = rep(1, pcod$OM@maxage),
           prior = pcod$prior)
          saveRDS(out@mean_fit$obj, file = "RCM_obj.rds")
          
          writeLines(c("library(SAMtool)",
          "assess_sim <- readRDS(\"assess_sim.rds\")",
          "for(i in 1:length(assess_sim)) {",
          "  print(names(assess_sim)[i])",
          "  assess_sim[[i]]@obj$retape()",
          "}",
          "assess_rs <- readRDS(\"assess_rs.rds\")",
          "for(i in 1:length(assess_rs)) {",
          "  print(names(assess_rs)[i])",
          "  assess_rs[[i]]@obj$retape()",
          "}",
          "RCM_obj <- readRDS(\"RCM_obj.rds\")",
          "RCM_obj$retape()"), 
                    con = "val.R")
        shell: RDscript {0}
      
      - name: Run valgrind
        run: RD -d valgrind --vanilla < val.R
